In [1]:
# CREATING NUMPY ARRAY
import numpy as np
 
# Creating a rank 1 Array
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [2]:
# Creating a rank 2 Array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [3]:
# Creating an array from tuple
arr = np.array((1, 3, 2))
print(arr)

[1 3 2]


In [4]:
# ACCESSING ARRAY INDEX
import numpy as np
 
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

# Printing a range of Array
# with the use of slicing method
arr2 = arr[:2, ::2]
print ("first 2 rows and alternate columns(0 and 2):\n", arr2)

first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]


In [5]:
# Printing elements at
# specific Indices
arr3 = arr[[1, 1, 0, 3], 
                [3, 2, 1, 0]]
print ("\nElements at indices (1, 3), "
    "(1, 2), (0, 1), (3, 0):\n", arr3)


Elements at indices (1, 3), (1, 2), (0, 1), (3, 0):
 [0. 6. 2. 3.]


In [6]:
# BASIC ARRAY OPERATIONS
import numpy as np
 
# Defining Array 1
a = np.array([[1, 2],
              [3, 4]])
 
# Defining Array 2
b = np.array([[4, 3],
              [2, 1]])
               
# Adding 1 to every element
print ("Adding 1 to every element:", a + 1)

Adding 1 to every element: [[2 3]
 [4 5]]


In [7]:
# Defining Array 1
a = np.array([[1, 2],
              [3, 4]])
 
# Defining Array 2
b = np.array([[4, 3],
              [2, 1]])

# Adding two arrays
# Performing Binary operations
print ("\nArray sum:\n", a + b)


Array sum:
 [[5 5]
 [5 5]]


In [8]:
# Defining Array 1
a = np.array([[1, 2],
              [3, 4]])
 
# Defining Array 2
b = np.array([[4, 3],
              [2, 1]])

# sum of array elements
# Performing Unary operations
print ("\nSum of all array elements: ", a.sum())
 


Sum of all array elements:  10


In [9]:
# Defining Array 1
a = np.array([[1, 2],
              [3, 4]])
 
# Defining Array 2
b = np.array([[4, 3],
              [2, 1]])

# Adding two arrays
# Performing Binary operations
print ("\nArray sum:\n", a + b)


Array sum:
 [[5 5]
 [5 5]]


In [10]:
# Defining Array 1
a = np.array([[1, 2],
              [3, 4]])
 
# Defining Array 2
b = np.array([[4, 3],
              [2, 1]])

# Adding two arrays
# Performing Binary operations
print ("\nArray sum:\n", a + b)


Array sum:
 [[5 5]
 [5 5]]


In [11]:
# MATH OPERATIONS ON DATA TYPE ARRAY
import numpy as np
 
# First Array
arr1 = np.array([[4, 7], [2, 6]], 
                 dtype = np.float64)
                  
# Second Array
arr2 = np.array([[3, 6], [2, 8]], 
                 dtype = np.float64) 
 
# Addition of two Arrays
Sum = np.add(arr1, arr2)
print(Sum)

[[ 7. 13.]
 [ 4. 14.]]


In [12]:
 
# First Array
arr1 = np.array([[4, 7], [2, 6]], 
                 dtype = np.float64)
                  
# Second Array
arr2 = np.array([[3, 6], [2, 8]], 
                 dtype = np.float64) 

# Addition of all Array elements
Sum1 = np.sum(arr1)
print(Sum1)
 

19.0
